const std = @import("std");
const glib = @import("abstract/graph.zig");
const Graph = glib.GateGraph;
const physical = @import("physical.zig");

// prioritize usage of horizontal wiring by punishing large y deviations more
const x_weight: f32 = 1;
const y_weight: f32 = 2;
const wire_cost_weight: f32 = 1;
const initial_spacing: u32 = 7;
const initial_row_size: u32 = 10;

pub const Orientation = enum {
    North,
    East,
    South,
    West,
};

pub const Position = struct { x: i32, y: i32, orientation: Orientation };

pub const Placement = struct {
    locations: std.AutoArrayHashMap(glib.NodeId, Position),

    pub fn clone(self: *const Placement, allocator: std.mem.Allocator) !*Placement {
        var placement = try allocator.create(Placement);
        placement.init(allocator);
        placement.locations = try self.locations.clone();
        return placement;
    }

    pub fn init(self: *Placement, allocator: std.mem.Allocator) void {
        self.locations = std.AutoArrayHashMap(glib.NodeId, Position).init(allocator);
    }

    pub fn deinit(self: *Placement, allocator: std.mem.Allocator) void {
        self.locations.deinit();
        allocator.destroy(self);
    }
};

// generated by chat :) \/\/
pub fn renderAscii(
    the_graph: *const Graph,
    placement: *const Placement,
    string: *std.io.Writer.Allocating,
) !void {
    var it = placement.locations.iterator();

    // --- 1. Compute bounds ---
    var min_x: i32 = std.math.maxInt(i32);
    var min_y: i32 = std.math.maxInt(i32);
    var max_x: i32 = std.math.minInt(i32);
    var max_y: i32 = std.math.minInt(i32);

    while (it.next()) |entry| {
        const r = entry.value_ptr.*;
        const id: glib.NodeId = entry.key_ptr.*;
        const node = the_graph.getConstNode(id).?;
        const w: i32 = @intCast(node.body.kind.size().w);
        const h: i32 = @intCast(node.body.kind.size().h);

        if (r.x < min_x) min_x = r.x;
        if (r.y < min_y) min_y = r.y;

        if (r.x + w > max_x) max_x = r.x + w;
        if (r.y + h > max_y) max_y = r.y + h;
    }

    const width: usize = @intCast(max_x - min_x);
    const height: usize = @intCast(max_y - min_y);

    // --- 2. Allocate dynamically ---
    var coverage = try string.allocator.alloc(u8, width * height);
    defer string.allocator.free(coverage);

    var grid = try string.allocator.alloc(u8, width * height);
    defer string.allocator.free(grid);

    // init
    for (coverage) |*c| c.* = 0;
    for (grid) |*g| g.* = '.';

    // --- 3. Render ---
    it = placement.locations.iterator();
    var idx: u8 = 0;

    var color_grid = try string.allocator.alloc(u8, width * height);
    defer string.allocator.free(color_grid);

    for (color_grid) |*c| c.* = 0;

    while (it.next()) |entry| {
        const r = entry.value_ptr.*;
        const id: glib.NodeId = entry.key_ptr.*;
        const node = the_graph.getConstNode(id).?;
        const w: i32 = @intCast(node.body.kind.size().w);
        const h: i32 = @intCast(node.body.kind.size().h);

        const group: u8 = idx / 26;
        const symbol: u8 = 'A' + (idx % 26);
        const color: u8 = colorForGroup(group);

        var dy: i32 = 0;
        while (dy < h) : (dy += 1) {
            var dx: i32 = 0;
            while (dx < w) : (dx += 1) {
                // --- normalize coordinates ---
                const gx = (r.x + dx) - min_x;
                const gy_world = (r.y + dy) - min_y;

                // --- flip Y for ASCII ---
                const gy = @as(i32, @intCast(height)) - 1 - gy_world;

                if (gx < 0 or gy < 0) continue;
                if (gx >= width or gy >= height) continue;

                const ux: usize = @intCast(gx);
                const uy: usize = @intCast(gy);

                const idx_flat = uy * width + ux;

                coverage[idx_flat] += 1;

                if (coverage[idx_flat] == 1) {
                    grid[idx_flat] = symbol;
                    color_grid[idx_flat] = color;
                } else {
                    grid[idx_flat] = 'X';
                    color_grid[idx_flat] = 196; // bright red
                }
            }
        }

        idx += 1;
    }

    // --- 4. Print ---
    var y: usize = 0;
    while (y < height) : (y += 1) {
        var x: usize = 0;
        while (x < width) : (x += 1) {
            const i = y * width + x;
            const ch = grid[i];

            if (ch == '.') {
                try string.writer.writeByte('.');
            } else {
                const color = color_grid[i];
                try string.writer.print("\x1b[38;5;{d}m{c}\x1b[0m", .{ color, ch });
            }
        }
        try string.writer.writeByte('\n');
    }
}
fn writeColoredChar(string: *std.io.Writer.Allocating, ch: u8, color_index: u8) !void {
    // 38;5;<n> = 256-color foreground
    try string.writer.print("\x1b[38;5;{d}m{c}\x1b[0m", .{ color_index, ch });
}
fn colorForGroup(group: u8) u8 {
    const colors = [_]u8{
        27, // blue
        46, // green
        226, // yellow
        201, // magenta
        51, // cyan
        196, // red
        208, // orange
        129, // purple
    };

    return colors[group % colors.len];
}
// end of generated by chat.

pub fn print(the_graph: *const Graph, placement: *Placement, allocator: std.mem.Allocator) void {
    errdefer @panic("Skill issue");

    var string = std.io.Writer.Allocating.init(allocator);
    try string.writer.writeAll("placement {\n");

    // var it = placement.locations.iterator();

    // while (it.next()) |entry| {
    //     try string.writer.print("   node:{d} (x:{d},y:{d});\n", .{ entry.key_ptr.*, entry.value_ptr.x, entry.value_ptr.y });
    // }

    // try string.writer.writeAll("}\n");

    try renderAscii(the_graph, placement, &string);
    std.debug.print("{s}", .{string.written()});

    string.deinit();
}

fn getAbsolutePosition(position: *const Position, port: @Vector(3, i32)) @Vector(2, i32) {
    // do not allow rotations for now
    return @Vector(2, i32){ position.x + port[0], position.y + port[2] };
}

// TODO: fix in-output positions to edges of board
// research showed no dependence between intial placement and final result, so lets do it computationally efficiently
fn initialPlacement(the_graph: *const Graph) *Placement {
    errdefer @panic("Ran out of memory lol");
    const placement = try the_graph.gpa.create(Placement);
    placement.init(the_graph.gpa);

    var x: i32 = 0;
    var y: i32 = 0;

    for (the_graph.nodes.keys()) |node_id| {
        try placement.locations.put(node_id, .{ .orientation = .North, .x = x, .y = y });
        std.debug.assert(placement.locations.count() > 0);
        x = x + initial_spacing;
        if (x >= initial_row_size * initial_spacing) {
            x = 0;
            y = y + initial_spacing;
        }
    }
    return placement;
}

// computes the cost of the given placement
fn cost(the_graph: *const Graph, the_placement: *const Placement) f32 {
    return costWireLength(the_graph, the_placement); // + costOverlap(the_graph, the_placement);
}

fn costWireLength(the_graph: *const Graph, the_placement: *const Placement) f32 {
    var sum: f32 = 0;
    for (the_graph.edges.values()) |net| {
        const pos_a = the_placement.locations.getPtr(net.a) orelse {
            std.debug.print("node 'net.a' {d} not placed\n", .{net.a});
            continue;
        };
        const pos_b = the_placement.locations.getPtr(net.b) orelse {
            std.debug.print("node 'net.b' {d} not placed\n", .{net.b});
            continue;
        };

        const node_a = the_graph.getConstNode(net.a).?;
        const node_b = the_graph.getConstNode(net.b).?;
        var from_node = node_a;
        var to_node = node_b;
        // inspired by graphviz.zig printedge
        const relation = node_a.edgeRelation(net.id) orelse @panic("Invalid edge?");
        if (relation == .input) {
            from_node = node_b;
            to_node = node_a;
        }
        const edges = the_graph.getNodeEdges(to_node.id, .input);
        var i: u8 = 0;
        while (edges[i] != net.id) {
            i += 1;
        }
        const port_output = from_node.body.kind.outputPositionsRelative();
        const port_input = to_node.body.kind.inputPositionsRelative()[i].?;

        const port_pos_a = getAbsolutePosition(pos_a, port_input);
        const port_pos_b = getAbsolutePosition(pos_b, port_output);

        const net_width = @as(f32, @floatFromInt(@abs(port_pos_a[0] - port_pos_b[0]))); // x
        const net_height = @as(f32, @floatFromInt(@abs(port_pos_a[1] - port_pos_b[1]))); // y

        sum = sum + net_width * x_weight + net_height * y_weight;
    }

    return wire_cost_weight * sum;
}

// fn costRowLength(the_placement: *Placement) f32 {
//     return 0;
// }

fn computeOverlapArea(the_graph: *const Graph, the_placement: *const Placement, i: glib.NodeId, j: glib.NodeId) f32 {
    if (i == j) return 0;

    const sizei = the_graph.getConstNode(i).?.body.kind.size();
    const sizej = the_graph.getConstNode(j).?.body.kind.size();
    const ipos = the_placement.locations.getPtr(i).?;
    const jpos = the_placement.locations.getPtr(j).?;

    const x_overlap = @max(0, @min(ipos.x + @as(i32, @intCast(sizei.w)), jpos.x + @as(i32, @intCast(sizej.w))) -
        @max(ipos.x, jpos.x));

    const y_overlap = @max(0, @min(ipos.y + @as(i32, @intCast(sizei.h)), jpos.y + @as(i32, @intCast(sizej.h))) -
        @max(ipos.y, jpos.y));

    return @floatFromInt(x_overlap * y_overlap);
}

// computationally expensive :(
fn costOverlap(the_graph: *const Graph, the_placement: *const Placement) f32 {
    var sum: f32 = 0;

    for (the_placement.locations.keys()) |i| {
        for (the_placement.locations.keys()) |j| {
            const overlap = computeOverlapArea(the_graph, the_placement, i, j);
            sum += overlap * overlap;
        }
    }

    return sum;
}

fn move(the_placement: *Placement, to_perturb: glib.NodeId, window_size: i32, random: std.Random) bool {
    errdefer @panic("Skill issue");
    var size_to_use = window_size;
    if (size_to_use < 5) {
        size_to_use = 5;
    }
    const new_x = random.intRangeLessThan(i32, -size_to_use, size_to_use);
    const new_y = random.intRangeLessThan(i32, -size_to_use, size_to_use);
    const orientation = the_placement.locations.getPtr(to_perturb).?.orientation;
    try the_placement.locations.put(to_perturb, .{ .x = new_x, .y = new_y, .orientation = orientation });
    return true;
}

// fn swap(the_placement: *Placement) bool {}

// fn mirror(the_placement: *Placement) bool {
//     // TODO: swap input connection of a and b, after we figure out how lol
// }

fn getRandomNodeID(
    the_placement: *const Placement,
    random: std.Random,
) ?glib.NodeId {
    const count = the_placement.locations.count();
    if (count == 0) return null;

    const index = random.intRangeLessThan(usize, 0, count);
    return the_placement.locations.keys()[index];
}

// randomly perturbs the placement
fn perturb(allocator: std.mem.Allocator, the_placement: *const Placement, random: std.Random, window_size: i32) *Placement {
    errdefer @panic("Ran out of memory lol");
    // TODO: doing this full deep copy every iteration seems expensive
    const new_placement = try the_placement.clone(allocator);

    const to_perturb = getRandomNodeID(new_placement, random).?;
    _ = move(new_placement, to_perturb, window_size, random);
    // TODO: complete perturbation of the new placement
    return new_placement;
}

// assigns a position to each cell in the graph, using the annealing placement algorithm.
pub fn placement_annealing(the_graph: *const Graph, initial_temperature: f32, minimum_temperature: f32, moves_per_temperature: u32, initial_window_size: f32) ?*Placement {
    var current_placement = initialPlacement(the_graph);
    print(the_graph, current_placement, the_graph.gpa);
    var temperature = initial_temperature;
    var current_window_size = initial_window_size;

    // get random generator:
    var seed: u32 = undefined;
    std.posix.getrandom(std.mem.asBytes(&seed)) catch |err| {
        std.debug.print("Failed to get random seed: {}\n", .{err});
        return null;
    };
    var prng = std.Random.DefaultPrng.init(seed);
    const rand = prng.random();

    // should be in (0,1)
    // should be a lower value at the start and end of the simulation, and a higher value in the middle, during refining.
    // it is constant for now.
    const alpha = 0.95;

    while (temperature > minimum_temperature) {
        var lastCost: f32 = std.math.floatMax(f32);
        for (0..moves_per_temperature) |i| {
            const new_placement = perturb(the_graph.gpa, current_placement, rand, @as(i32, @intFromFloat(current_window_size)));
            // std.debug.print("node 3 is placed here: {d}, {d}\n", .{ current_placement.locations.get(3).?.x, current_placement.locations.get(3).?.y });
            const current_cost = cost(the_graph, current_placement);
            const new_cost = cost(the_graph, new_placement);
            const cost_diff = new_cost - current_cost;
            // std.debug.print("costs: {d}, {d}\n", .{ current_cost, new_cost });
            if (cost_diff < 0) {
                current_placement.deinit(the_graph.gpa);
                current_placement = new_placement;
                lastCost = new_cost;
            } else {
                const value = rand.float(f32);
                // compute e^(-Δcost/T):
                const exponent = (-cost_diff / temperature);
                if (value < std.math.exp(exponent)) {
                    current_placement.deinit(the_graph.gpa);
                    current_placement = new_placement;
                    lastCost = new_cost;
                } else {
                    new_placement.deinit(the_graph.gpa);
                    lastCost = current_cost;
                }
            }
            const progress = (@as(f32, @floatFromInt(i)) / @as(f32, @floatFromInt(moves_per_temperature))) * 100;
            if (moves_per_temperature > 100) {
                // print every 10%
                if (i % (moves_per_temperature / 10) == 0) {
                    std.log.info(
                        "{d}% progress of Temp: {d}, Cost: {d}",
                        .{ progress, temperature, lastCost },
                    );
                }
            }
        } // exit loop if in equilibrium at this temperature

        print(the_graph, current_placement, the_graph.gpa);

        std.log.info(
            "Cost: {d}, Temp: {d}\n",
            .{ lastCost, temperature },
        );
        // compute wnext=wcurr*(log(tnext)/log(tcurr)):
        current_window_size = current_window_size * (std.math.log10(temperature * alpha) / std.math.log10(temperature));
        // compute tnext:
        temperature *= alpha;
    }
    return current_placement;
}

// pseudo code:

// Simulated Annealing Algorithm for Placement
// Input: set of all cells V
// Output: placement P
// 1 T=T0
// 2 P=PLACE(V)
// 3 while(T>Tmin)
// 4 while(!STOP())
// new_P =PERTURB(P)
// Δcost =COST(new_P)–COST(P)
// if (Δcost <0)
// P =new_P
// else
// r =RANDOM(0,1)
// 11 if(r<e^(-Δcost/T))
// P =new_P
// T=α∙T
