const std = @import("std");
const glib = @import("abstract/graph.zig");
const Graph = glib.GateGraph;
const physical = @import("physical.zig");

// comptime or private variables:
// since schematic doesnt use negative coordinates, lets not bother with it here
pub const postype = u32;
const use_accurate_input_pos = false;
const max_chipsize: u32 = 100;
// used to avoid reading out of index in the grid
const max_cell_size: u32 = 6;

pub const AnnealingConfig = struct {
    // - "The annealing process starts at a high temperature, such as 4*10^6"
    // From a first quick run, this is way too high lmao, it really doesnt find any improvements at that temperature.
    // around 30 seems fine
    initial_temperature: f32 = 30,
    minimum_temperature: f32 = 1,
    // - "The authors of [28] experimentally determined that designs with ~200 cells require
    // 100 iterations per cell, or roughly 2 *10^4 runs per temperature step."
    // so, for us it would be around 10^4 runs.
    moves_per_temperature: u32 = 10000,
    // - "we start at a window size of twice the chip size"
    // since chip bounds are currently not taken into acount, we pick 100 for now
    initial_window_size: f32 = 100,
    // - perturbations amount = 1 causes the cost to decrease way more effectively as temp decreases, although runtime increases
    perturbations_amount: u32 = 1,
    // we could prioritize usage of horizontal wiring by punishing large y deviations more
    x_weight: f32 = 1,
    y_weight: f32 = 1,
    wire_cost_weight: f32 = 1,
    // initial placement is completely independent from final result
    initial_spacing: postype = 6,
    initial_row_size: postype = 15,
    // 2*2 grid segments
    grid_size: u8 = 2,
    // fix all in-output nodes to the same y axis
    initial_input_y: postype = 70,
    initial_output_y: postype = 0,
};

pub const Orientation = enum {
    North,
    East,
    South,
    West,
};

pub const Position = struct { x: postype, y: postype, orientation: Orientation };

pub const Placement = struct {
    locations: std.AutoArrayHashMap(glib.NodeId, Position),
    occupancy_grid: [max_chipsize + max_cell_size][max_chipsize + max_cell_size]glib.NodeId,
    output_y: postype, // to fix all outputs to this y position
    input_y: postype, // to fix all inputs to this y position
    output_nodes: std.AutoArrayHashMap(glib.NodeId, void),
    input_nodes: std.AutoArrayHashMap(glib.NodeId, void),

    pub fn clone(self: *const Placement, allocator: std.mem.Allocator) !*Placement {
        var placement = try allocator.create(Placement);
        placement.locations = try self.locations.clone();
        placement.occupancy_grid = self.occupancy_grid;
        placement.output_y = self.output_y;
        placement.input_y = self.input_y;
        placement.output_nodes = try self.output_nodes.clone();
        placement.input_nodes = try self.input_nodes.clone();
        return placement;
    }

    pub fn init(self: *Placement, allocator: std.mem.Allocator) void {
        self.locations = std.AutoArrayHashMap(glib.NodeId, Position).init(allocator);
        self.occupancy_grid = std.mem.zeroes([max_chipsize + max_cell_size][max_chipsize + max_cell_size]glib.NodeId);
        self.output_y = 0;
        self.input_y = 0;
        self.output_nodes = std.AutoArrayHashMap(glib.NodeId, void).init(allocator);
        self.input_nodes = std.AutoArrayHashMap(glib.NodeId, void).init(allocator);
    }

    pub fn deinit(self: *Placement, allocator: std.mem.Allocator) void {
        self.locations.deinit();
        self.input_nodes.deinit();
        self.output_nodes.deinit();
        allocator.destroy(self);
    }
};

// generated by chat :) \/\/
pub fn renderAscii(
    the_graph: *const Graph,
    placement: *const Placement,
    string: *std.io.Writer.Allocating,
) !void {
    var it = placement.locations.iterator();

    // --- 1. Compute bounds ---
    var min_x: postype = std.math.maxInt(postype);
    var min_y: postype = std.math.maxInt(postype);
    var max_x: postype = std.math.minInt(postype);
    var max_y: postype = std.math.minInt(postype);

    while (it.next()) |entry| {
        const r = entry.value_ptr.*;
        const id: glib.NodeId = entry.key_ptr.*;
        const node = the_graph.getConstNode(id).?;
        const w: postype = @intCast(node.body.kind.size().w);
        const h: postype = @intCast(node.body.kind.size().h);

        if (r.x < min_x) min_x = r.x;
        if (r.y < min_y) min_y = r.y;

        if (r.x + w > max_x) max_x = r.x + w;
        if (r.y + h > max_y) max_y = r.y + h;
    }

    const width: usize = @intCast(max_x - min_x);
    const height: usize = @intCast(max_y - min_y);

    // --- 2. Allocate dynamically ---
    var coverage = try string.allocator.alloc(u8, width * height);
    defer string.allocator.free(coverage);

    var grid = try string.allocator.alloc(u8, width * height);
    defer string.allocator.free(grid);

    // init
    for (coverage) |*c| c.* = 0;
    for (grid) |*g| g.* = '.';

    // --- 3. Render ---
    it = placement.locations.iterator();
    var idx: u8 = 0;

    var color_grid = try string.allocator.alloc(u8, width * height);
    defer string.allocator.free(color_grid);

    for (color_grid) |*c| c.* = 0;

    while (it.next()) |entry| {
        const r = entry.value_ptr.*;
        const id: glib.NodeId = entry.key_ptr.*;
        const node = the_graph.getConstNode(id).?;
        const w: postype = @intCast(node.body.kind.size().w);
        const h: postype = @intCast(node.body.kind.size().h);

        const group: u8 = idx / 26;
        const symbol: u8 = 'A' + (idx % 26);
        const color: u8 = colorForGroup(group);

        var dy: postype = 0;
        while (dy < h) : (dy += 1) {
            var dx: postype = 0;
            while (dx < w) : (dx += 1) {
                // --- normalize coordinates ---
                const gx = (r.x + dx) - min_x;
                const gy_world = (r.y + dy) - min_y;

                // --- flip Y for ASCII ---
                const gy = @as(postype, @intCast(height)) - 1 - gy_world;

                if (gx < 0 or gy < 0) continue;
                if (gx >= width or gy >= height) continue;

                const ux: usize = @intCast(gx);
                const uy: usize = @intCast(gy);

                const idx_flat = uy * width + ux;

                coverage[idx_flat] += 1;

                if (coverage[idx_flat] == 1) {
                    grid[idx_flat] = symbol;
                    color_grid[idx_flat] = color;
                } else {
                    grid[idx_flat] = 'X';
                    color_grid[idx_flat] = 196; // bright red
                }
            }
        }

        idx += 1;
    }

    // --- 4. Print ---
    var y: usize = 0;
    while (y < height) : (y += 1) {
        var x: usize = 0;
        while (x < width) : (x += 1) {
            const i = y * width + x;
            const ch = grid[i];

            if (ch == '.') {
                try string.writer.writeByte('.');
            } else {
                const color = color_grid[i];
                try string.writer.print("\x1b[38;5;{d}m{c}\x1b[0m", .{ color, ch });
            }
        }
        try string.writer.writeByte('\n');
    }
}
fn writeColoredChar(string: *std.io.Writer.Allocating, ch: u8, color_index: u8) !void {
    // 38;5;<n> = 256-color foreground
    try string.writer.print("\x1b[38;5;{d}m{c}\x1b[0m", .{ color_index, ch });
}
fn colorForGroup(group: u8) u8 {
    const colors = [_]u8{
        27, // blue
        46, // green
        226, // yellow
        201, // magenta
        51, // cyan
        196, // red
        208, // orange
        129, // purple
    };

    return colors[group % colors.len];
}

pub fn printGrid(self: *const Placement, string: *std.io.Writer.Allocating) void {
    var y: usize = 100;
    while (y > 0) {
        y -= 1; // now y goes: 299 → 0

        for (0..100) |x| {
            string.writer.print("{:>3}", .{self.occupancy_grid[x][y]}) catch {};
        }
        string.writer.print("\n", .{}) catch {};
    }
}
// end of generated by chat.

pub fn print(the_graph: *const Graph, placement: *Placement, allocator: std.mem.Allocator) void {
    errdefer @panic("Skill issue");

    var string = std.io.Writer.Allocating.init(allocator);
    try string.writer.writeAll("placement {\n");

    // var it = placement.locations.iterator();

    // while (it.next()) |entry| {
    //     try string.writer.print("   node:{d} (x:{d},y:{d});\n", .{ entry.key_ptr.*, entry.value_ptr.x, entry.value_ptr.y });
    // }

    // try string.writer.writeAll("}\n");

    try renderAscii(the_graph, placement, &string);

    // printGrid(placement, &string);
    std.debug.print("{s}", .{string.written()});

    string.deinit();
}

// not O(1) :(
fn isOutput(the_graph: *const Graph, node_id: glib.NodeId) bool {
    return (the_graph.getNodeEdges(node_id, .output).len == 0);
}

// not O(1) :(
fn isInput(the_graph: *const Graph, node_id: glib.NodeId) bool {
    return (the_graph.getNodeEdges(node_id, .input).len == 0);
}

fn getAbsolutePosition(position: *const Position, port_pos_relative: @Vector(3, i32), min_pos: postype) @Vector(2, postype) {
    // do not allow rotations for now
    // this would cause pain for computewirelength if negative:
    std.debug.assert(@as(i32, @intCast(position.x)) + port_pos_relative[0] >= 0);
    std.debug.assert(@as(i32, @intCast(position.x)) + port_pos_relative[2] >= 0);

    const new_x = clampU32WithDelta(position.x, port_pos_relative[0], max_chipsize, min_pos);
    const new_y = clampU32WithDelta(position.y, port_pos_relative[2], max_chipsize, min_pos);

    return @Vector(2, postype){ new_x, new_y };
}

// research showed no dependence between intial placement and final result, so lets do it computationally efficiently
fn initialPlacement(the_graph: *const Graph, annealing_config: AnnealingConfig) *Placement {
    errdefer @panic("Ran out of memory lol");
    const placement = try the_graph.gpa.create(Placement);
    placement.init(the_graph.gpa);
    placement.input_y = annealing_config.initial_input_y;
    placement.output_y = annealing_config.initial_output_y;

    // place input nodes:
    var x: postype = 1 * annealing_config.grid_size;
    var y: postype = annealing_config.initial_input_y;

    var count: u32 = 0;

    for (the_graph.nodes.keys()) |node_id| {
        if (isInput(the_graph, node_id)) {
            try place(placement, the_graph.getConstNode(node_id).?, x, y, .North);
            try placement.input_nodes.put(node_id, {});
            count += 1;
            std.debug.assert(placement.locations.count() == count);
            std.debug.print("placed {d} at ({d},{d})\n", .{ node_id, x, y });
            x = x + annealing_config.initial_spacing;
        }
    }

    // place output nodes:
    x = 1 * annealing_config.grid_size;
    y = annealing_config.initial_output_y;

    for (the_graph.nodes.keys()) |node_id| {
        if (isOutput(the_graph, node_id)) {
            try place(placement, the_graph.getConstNode(node_id).?, x, y, .North);
            try placement.output_nodes.put(node_id, {});
            count += 1;
            std.debug.assert(placement.locations.count() == count);
            std.debug.print("placed {d} at ({d},{d})\n", .{ node_id, x, y });
            x = x + annealing_config.initial_spacing;
        }
    }

    x = 1 * annealing_config.grid_size;
    y = 1 * annealing_config.grid_size;

    for (the_graph.nodes.keys()) |node_id| {
        if (isOutput(the_graph, node_id) or isInput(the_graph, node_id)) {
            continue;
        }
        try place(placement, the_graph.getConstNode(node_id).?, x, y, .North);
        count += 1;
        std.debug.assert(placement.locations.count() == count);
        x = x + annealing_config.initial_spacing;
        if (x >= annealing_config.initial_row_size * annealing_config.initial_spacing) {
            x = 1 * annealing_config.grid_size;
            y = y + annealing_config.initial_spacing;
        }
    }
    return placement;
}

// computes the cost of the given placement
fn cost(the_graph: *const Graph, the_placement: *const Placement, annealing_config: AnnealingConfig) f32 {
    return costWireLength(the_graph, the_placement, annealing_config); // + costOverlap(the_graph, the_placement);
}

fn costWireLength(the_graph: *const Graph, the_placement: *const Placement, annealing_config: AnnealingConfig) f32 {
    var sum: f32 = 0;
    for (the_graph.edges.values()) |net| {
        const pos_a = the_placement.locations.getPtr(net.a) orelse {
            std.debug.print("node 'net.a' {d} not placed\n", .{net.a});
            continue;
        };
        const pos_b = the_placement.locations.getPtr(net.b) orelse {
            std.debug.print("node 'net.b' {d} not placed\n", .{net.b});
            continue;
        };

        var from_node_id = net.a;
        var to_node_id = net.b;
        if (net.a_relation == .input) {
            from_node_id = net.b;
            to_node_id = net.a;
        }
        const from_node = the_graph.getConstNode(from_node_id).?;
        const to_node = the_graph.getConstNode(to_node_id).?;

        var i: u8 = 0;
        if (use_accurate_input_pos) {
            // made compile time optional
            const edges = the_graph.getNodeEdges(to_node_id, .input);

            while (edges[i] != net.id) {
                i += 1;
            }
        }
        const port_output = from_node.body.kind.outputPositionsRelative();
        const port_input = to_node.body.kind.inputPositionsRelative()[i].?;

        // if this fails, positions are clamped to 0 and not accurate
        std.debug.assert(@as(i32, @intCast(pos_a.x)) + port_input[0] >= 0);
        std.debug.assert(@as(i32, @intCast(pos_a.y)) + port_input[0] >= 0);
        std.debug.assert(@as(i32, @intCast(pos_b.x)) + port_output[2] >= 0);
        std.debug.assert(@as(i32, @intCast(pos_b.y)) + port_output[2] >= 0);

        const port_pos_a = getAbsolutePosition(pos_a, port_input, 0);
        const port_pos_b = getAbsolutePosition(pos_b, port_output, 0);

        const diff_x = if (port_pos_a[0] > port_pos_b[0]) port_pos_a[0] - port_pos_b[0] else port_pos_b[0] - port_pos_a[0];
        const net_width = @as(f32, @floatFromInt(diff_x));
        const diff_y = if (port_pos_a[1] > port_pos_b[1]) port_pos_a[1] - port_pos_b[1] else port_pos_b[1] - port_pos_a[1];
        const net_height = @as(f32, @floatFromInt(diff_y));

        sum = sum + net_width * annealing_config.x_weight + net_height * annealing_config.y_weight;
    }

    return annealing_config.wire_cost_weight * sum;
}

// depricated, movements now do not cause overlap at all
fn computeOverlapArea(the_graph: *const Graph, the_placement: *const Placement, i: glib.NodeId, j: glib.NodeId) f32 {
    if (i == j) return 0;

    const sizei = the_graph.getConstNode(i).?.body.kind.size();
    const sizej = the_graph.getConstNode(j).?.body.kind.size();
    const ipos = the_placement.locations.getPtr(i).?;
    const jpos = the_placement.locations.getPtr(j).?;

    const x_overlap = @max(0, @min(ipos.x + @as(i32, @intCast(sizei.w)), jpos.x + @as(i32, @intCast(sizej.w))) -
        @max(ipos.x, jpos.x));

    const y_overlap = @max(0, @min(ipos.y + @as(i32, @intCast(sizei.h)), jpos.y + @as(i32, @intCast(sizej.h))) -
        @max(ipos.y, jpos.y));

    return @floatFromInt(x_overlap * y_overlap);
}

// computationally expensive :(
// but unused, since movements do not cause overlaps
fn costOverlap(the_graph: *const Graph, the_placement: *const Placement) f32 {
    var sum: f32 = 0;

    for (the_placement.locations.keys()) |i| {
        for (the_placement.locations.keys()) |j| {
            const overlap = computeOverlapArea(the_graph, the_placement, i, j);
            sum += overlap * overlap;
        }
    }

    return sum;
}

// places node at position without checking for collisions, used by initial placement.
fn place(the_placement: *Placement, to_place: *const glib.GateGraph.Node, new_x: postype, new_y: postype, orientation: Orientation) !void {
    const rect = to_place.body.kind.size();
    for (new_x..new_x + rect.w) |x| {
        for (new_y..new_y + rect.h) |y| {
            the_placement.occupancy_grid[x][y] = to_place.id;
        }
    }

    try the_placement.locations.put(to_place.id, .{ .orientation = orientation, .x = new_x, .y = new_y });
}

// tries to move a node to a new position, checking for collisions.
// Returns 0 if move was succesful and without collisions
// Returns the nodeid of the collision.
fn tryMove(the_placement: *Placement, to_place: *const glib.GateGraph.Node, last_pos: *const Position, new_x: postype, new_y: postype) !glib.NodeId {
    // const node = the_graph.getConstNode(to_place);
    const rect = to_place.body.kind.size();

    const collision_result = try checkCollision(the_placement, to_place.id, rect, new_x, new_y);
    if (collision_result != 0) return collision_result;

    // No collision, so move rectangle
    for (last_pos.x..last_pos.x + rect.w) |x| {
        for (last_pos.y..last_pos.y + rect.h) |y| {
            the_placement.occupancy_grid[x][y] = 0;
        }
    }

    try place(the_placement, to_place, new_x, new_y, last_pos.orientation);
    return 0;
}

fn checkCollision(the_placement: *const Placement, node_id: glib.NodeId, size: physical.Size, new_x: postype, new_y: postype) !glib.NodeId {
    for (new_x..new_x + size.w) |x| {
        for (new_y..new_y + size.h) |y| {
            if (the_placement.occupancy_grid[x][y] != 0 and the_placement.occupancy_grid[x][y] != node_id) {
                return the_placement.occupancy_grid[x][y];
            }
        }
    }
    return 0;
}

fn clampU32WithDelta(x: postype, dx: i32, max_pos: postype, min_pos: postype) postype {
    var wide: i64 = @as(i64, x) + @as(i64, dx);

    if (wide < min_pos) wide = min_pos;
    if (wide > max_pos) wide = max_pos;

    return @as(postype, @intCast(wide));
}

// picks a new random position for a given node.
// the new position will never be further away from the original than window_size
// Returns 0 if move was succesful and without collisions
// Returns the nodeid of the collision.
fn randomMove(the_graph: *const Graph, the_placement: *Placement, to_perturb: glib.NodeId, window_size: u32, random: std.Random, min_spacing: u8, min_pos: postype, fixed_y_pos: ?postype) glib.NodeId {
    errdefer @panic("Skill issue");
    var size_to_use: i32 = @intCast(window_size);
    if (size_to_use < min_spacing) {
        size_to_use = min_spacing;
    }
    size_to_use = @divFloor(size_to_use, min_spacing);

    const pos = the_placement.locations.getPtr(to_perturb).?;

    // these normalizations are to keep the random normally distributed, so it may be omitted for performance just fine.
    const min_to_use_x: i32 = -@min(@divFloor(pos.x - min_pos, min_spacing), size_to_use);
    const max_to_use_x: i32 = @min(@divFloor(max_chipsize - pos.x, min_spacing), size_to_use);

    const dx = random.intRangeLessThan(i32, min_to_use_x, max_to_use_x) * min_spacing;
    const new_x: postype = clampU32WithDelta(pos.x, dx, max_chipsize, min_pos);

    var new_y: ?postype = fixed_y_pos;
    if (fixed_y_pos == null) {
        const min_to_use_y: i32 = -@min(@divFloor(pos.y - min_pos, min_spacing), size_to_use);
        const max_to_use_y: i32 = @min(@divFloor(max_chipsize - pos.y, min_spacing), size_to_use);

        const dy = random.intRangeLessThan(i32, min_to_use_y, max_to_use_y) * min_spacing;
        new_y = clampU32WithDelta(pos.y, dy, max_chipsize, min_pos);
    }

    const result = try tryMove(the_placement, the_graph.getConstNode(to_perturb).?, pos, new_x, new_y.?);
    if (fixed_y_pos != null) {
        std.debug.assert(fixed_y_pos == the_placement.locations.getPtr(to_perturb).?.y);
    }
    return result;
}

// attempts to swap the 2 nodes given
// if both fit at the new locations without collisions, it performs the swap and returns true.
fn swap(the_graph: *const Graph, the_placement: *Placement, node_a_id: glib.NodeId, node_b_id: glib.NodeId) bool {
    errdefer @panic("Skill issue");
    if (isInput(the_graph, node_a_id) or isOutput(the_graph, node_a_id)) {
        return false;
    }
    if (isInput(the_graph, node_b_id) or isOutput(the_graph, node_b_id)) {
        return false;
    }

    const node_a = the_graph.getConstNode(node_a_id).?;
    const node_b = the_graph.getConstNode(node_b_id).?;
    const rect_a = node_a.body.kind.size();
    const rect_b = node_b.body.kind.size();
    const pos_a = the_placement.locations.getPtr(node_a_id).?;
    const pos_b = the_placement.locations.getPtr(node_b_id).?;

    const unsigned_new_x_a = pos_b.x;
    const unsigned_new_y_a = pos_b.y;

    // check whether a fits at b position
    for (unsigned_new_x_a..unsigned_new_x_a + rect_a.w) |x| {
        for (unsigned_new_y_a..unsigned_new_y_a + rect_a.h) |y| {
            if (the_placement.occupancy_grid[x][y] != 0 and the_placement.occupancy_grid[x][y] != node_b_id) {
                return false;
            }
        }
    }

    const unsigned_new_x_b = pos_a.x;
    const unsigned_new_y_b = pos_a.y;

    // check whether b fits at a position
    for (unsigned_new_x_b..unsigned_new_x_b + rect_b.w) |x| {
        for (unsigned_new_y_b..unsigned_new_y_b + rect_b.h) |y| {
            if (the_placement.occupancy_grid[x][y] != 0 and the_placement.occupancy_grid[x][y] != node_a_id) {
                return false;
            }
        }
    }

    // both fit, so proceed the swap:
    // set both old positions to 0:
    for (unsigned_new_x_b..unsigned_new_x_b + rect_a.w) |x| {
        for (unsigned_new_y_b..unsigned_new_y_b + rect_a.h) |y| {
            the_placement.occupancy_grid[x][y] = 0;
        }
    }
    for (unsigned_new_x_a..unsigned_new_x_a + rect_b.w) |x| {
        for (unsigned_new_y_a..unsigned_new_y_a + rect_b.h) |y| {
            the_placement.occupancy_grid[x][y] = 0;
        }
    }

    // set a to b position
    try place(the_placement, node_a, unsigned_new_x_a, unsigned_new_y_a, pos_a.orientation);
    // set b to a position
    try place(the_placement, node_b, unsigned_new_x_b, unsigned_new_y_b, pos_b.orientation);

    return true;
}

// fn mirror(the_placement: *Placement) bool {
//     // TODO: swap input connection of a and b, only useful if use accurate input positions are used to calculate wirelength cost
// }

fn moveInputAxis(the_graph: *const Graph, the_placement: *Placement, window_size: u32, random: std.Random, min_spacing: u8, min_pos: postype) glib.NodeId {
    errdefer @panic("Skill issue");
    var size_to_use: i32 = @intCast(window_size);
    if (size_to_use < min_spacing) {
        size_to_use = min_spacing;
    }
    size_to_use = @divFloor(size_to_use, min_spacing);
    const min_to_use: i32 = -@min(@divFloor(the_placement.input_y, min_spacing), size_to_use);

    const dy = random.intRangeLessThan(i32, min_to_use, size_to_use) * min_spacing;
    const new_y: postype = clampU32WithDelta(the_placement.input_y, dy, max_chipsize, min_pos);
    var lasytpos: ?postype = null;
    // check for collisions:
    var it1 = the_placement.input_nodes.iterator();
    while (it1.next()) |entry| {
        const id: glib.NodeId = entry.key_ptr.*;
        const rect = the_graph.getConstNode(id).?.body.kind.size();
        const pos = the_placement.locations.getPtr(id).?;
        if (lasytpos == null) {
            lasytpos = pos.y;
        }
        std.debug.assert(lasytpos == pos.y);

        const collision_result = try checkCollision(the_placement, id, rect, pos.x, new_y);
        if (collision_result != 0) return collision_result;
    }

    // no collision: move all nodes to new position:
    var it2 = the_placement.input_nodes.iterator();
    while (it2.next()) |entry| {
        const id: glib.NodeId = entry.key_ptr.*;
        const pos = the_placement.locations.getPtr(id).?;
        const node = the_graph.getConstNode(id).?;
        const rect = node.body.kind.size();
        const before = try checkCollision(the_placement, id, rect, pos.x, new_y);
        const result = try tryMove(the_placement, node, pos, pos.x, new_y);
        // std.debug.print("moved once {d},{d}", .{ before, result });
        std.debug.assert(before == 0);
        std.debug.assert(result == 0);
    }
    the_placement.input_y = new_y;

    return 0;
}

fn getRandomNodeID(
    the_placement: *const Placement,
    random: std.Random,
) ?glib.NodeId {
    const count = the_placement.locations.count();
    if (count == 0) return null;

    const index = random.intRangeLessThan(usize, 0, count);
    return the_placement.locations.keys()[index];
}

// randomly perturbs the placement
fn perturb(the_graph: *const Graph, the_placement: *Placement, random: std.Random, current_window_size: f32, annealing_config: AnnealingConfig) void {
    errdefer @panic("Ran out of memory lol");
    for (0..annealing_config.perturbations_amount) |_| {
        const to_perturb = getRandomNodeID(the_placement, random).?;
        if (isOutput(the_graph, to_perturb)) {
            _ = randomMove(the_graph, the_placement, to_perturb, @intFromFloat(@ceil(current_window_size)), random, annealing_config.grid_size, annealing_config.grid_size, the_placement.output_y);
        } else if (isInput(the_graph, to_perturb)) {
            // perform moveOutput 1 out of 10 times
            if (random.intRangeLessThan(usize, 0, 10) != 1) {
                _ = randomMove(the_graph, the_placement, to_perturb, @intFromFloat(@ceil(current_window_size)), random, annealing_config.grid_size, annealing_config.grid_size, the_placement.input_y);
            } else {
                _ = moveInputAxis(the_graph, the_placement, @intFromFloat(@ceil(current_window_size)), random, annealing_config.grid_size, annealing_config.grid_size);
            }

            // _ = moveRandomFixedY(the_graph, the_placement, to_perturb, @intFromFloat(@ceil(current_window_size)), random, annealing_config.grid_size, annealing_config.grid_size, the_placement.input_y);
        } else {
            const result = randomMove(the_graph, the_placement, to_perturb, @intFromFloat(@ceil(current_window_size)), random, annealing_config.grid_size, annealing_config.grid_size, null); // use grid size as the minimum y position, so it stays nicely alligned if we changed it in the future
            if (result != 0) {
                _ = swap(the_graph, the_placement, to_perturb, result);
            }
        }
        // TODO: add mirror or other perturbations
    }
}

// assigns a position to each cell in the graph, using the annealing placement algorithm.
// pseudo code:

// Simulated Annealing Algorithm for Placement
// Input: set of all cells V
// Output: placement P
// 1 T=T0
// 2 P=PLACE(V)
// 3 while(T>Tmin)
// 4 while(!STOP())
// new_P =PERTURB(P)
// Δcost =COST(new_P)–COST(P)
// if (Δcost <0)
// P =new_P
// else
// r =RANDOM(0,1)
// 11 if(r<e^(-Δcost/T))
// P =new_P
// T=α∙T

pub fn placement_annealing(the_graph: *const Graph, annealing_config: AnnealingConfig) ?*Placement {
    errdefer @panic("Skill issue");

    var current_placement = initialPlacement(the_graph, annealing_config);
    print(the_graph, current_placement, the_graph.gpa);
    var temperature = annealing_config.initial_temperature;
    var current_window_size = annealing_config.initial_window_size;

    // get random generator:
    var seed: u32 = undefined;
    std.posix.getrandom(std.mem.asBytes(&seed)) catch |err| {
        std.debug.print("Failed to get random seed: {}\n", .{err});
        return null;
    };
    var prng = std.Random.DefaultPrng.init(seed);
    const rand = prng.random();

    // should be in (0,1)
    // should be a lower value at the start and end of the simulation, and a higher value in the middle, during refining.
    // it is constant for now.
    const alpha = 0.95;
    const actual_moves_per_temperature = @divFloor(annealing_config.moves_per_temperature, annealing_config.perturbations_amount);

    var lastCost: f32 = cost(the_graph, current_placement, annealing_config);
    while (temperature > annealing_config.minimum_temperature) {
        for (0..actual_moves_per_temperature) |i| {
            var new_placement = try current_placement.clone(the_graph.gpa);

            perturb(the_graph, new_placement, rand, current_window_size, annealing_config);
            const current_cost = lastCost;
            const new_cost = cost(the_graph, new_placement, annealing_config);
            const cost_diff = new_cost - current_cost;
            if (cost_diff < 0) {
                current_placement.deinit(the_graph.gpa);
                current_placement = new_placement;
                lastCost = new_cost;
            } else {
                const value = rand.float(f32);
                // compute e^(-Δcost/T):
                const exponent = (-cost_diff / temperature);
                if (value < std.math.exp(exponent)) {
                    current_placement.deinit(the_graph.gpa);
                    current_placement = new_placement;
                    lastCost = new_cost;
                } else {
                    new_placement.deinit(the_graph.gpa);
                    lastCost = current_cost;
                }
            }
            const progress = (@as(f32, @floatFromInt(i)) / @as(f32, @floatFromInt(actual_moves_per_temperature))) * 100;
            if (actual_moves_per_temperature > 100) {
                // print every 10%
                if (i % (actual_moves_per_temperature / 10) == 0) {
                    std.log.info(
                        "{d}% progress of Temp: {d}, Cost: {d}",
                        .{ progress, temperature, lastCost },
                    );
                }
            }
        } // exit loop if in equilibrium at this temperature

        print(the_graph, current_placement, the_graph.gpa);
        std.log.info(
            "Cost: {d}, Temp: {d}, windowsize: {d}\n",
            .{ lastCost, temperature, current_window_size },
        );
        // compute wnext=wcurr*(log(tnext)/log(tcurr)):
        current_window_size = current_window_size * (std.math.log10(temperature * alpha) / std.math.log10(temperature));
        // compute tnext:
        temperature *= alpha;
    }
    return current_placement;
}
